"""Utilities for German BESS statistics from the Marktstammdatenregister.

The preferred path is to process a local MaStR storage export, for example a
table generated by ``open-mastr``. The checked-in dashboard snapshot is a small
MaStR-derived April 2026 aggregate so the educational app stays fast and usable
without downloading the multi-gigabyte bulk registry at runtime.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[2]
PROCESSED_STATS_PATH = PROJECT_ROOT / "data" / "processed" / "mastr_bess_stats.parquet"
MASTR_STAND = "April 2026"
MASTR_SOURCE = "Bundesnetzagentur - MaStR"
MASTR_SOURCE_URL = "https://www.marktstammdatenregister.de/"


def _base_row(
    *,
    section: str,
    label: str,
    value: float | int | None = None,
    unit: str = "",
    capacity_mwh: float | None = None,
    power_mw: float | None = None,
    systems: int | None = None,
    average_epr_h: float | None = None,
    share_pct: float | None = None,
    notes: str = "",
    sort_order: int = 0,
) -> dict[str, object]:
    """Return one normalized stat row for Streamlit and Parquet consumers."""

    return {
        "section": section,
        "label": label,
        "value": value,
        "unit": unit,
        "capacity_mwh": capacity_mwh,
        "power_mw": power_mw,
        "systems": systems,
        "average_epr_h": average_epr_h,
        "share_pct": share_pct,
        "source": MASTR_SOURCE,
        "source_url": MASTR_SOURCE_URL,
        "stand": MASTR_STAND,
        "data_label": "Real Data",
        "notes": notes,
        "sort_order": sort_order,
    }


def curated_april_2026_bess_snapshot() -> pd.DataFrame:
    """Return a compact real-data snapshot derived from public MaStR aggregates.

    Sources used for the shipped snapshot:
    - Bundesnetzagentur MaStR public registry as underlying source.
    - Public April 2026 MaStR/Battery Charts reporting for national stock:
      27.23 GWh usable capacity, 17.90 GW power, more than 2.4 million systems.
    - Public IWR/Speicherbranche MaStR v2 reporting for Q1 2026 Bundesland
      capacity additions and segment totals.

    The EPR rows are segment-derived buckets for education. Processing a raw
    MaStR export with ``process_mastr_bess_units`` creates row-level EPR buckets.
    """

    total_capacity_mwh = 27_230.0
    total_power_mw = 17_900.0
    total_systems = 2_400_000
    average_epr_h = total_capacity_mwh / total_power_mw

    rows: list[dict[str, object]] = [
        _base_row(
            section="summary",
            label="Total installed storage capacity",
            value=total_capacity_mwh,
            unit="MWh",
            capacity_mwh=total_capacity_mwh,
            power_mw=total_power_mw,
            systems=total_systems,
            average_epr_h=average_epr_h,
            notes="Cumulative German registered battery storage stock, MaStR-derived public aggregate.",
            sort_order=1,
        ),
        _base_row(
            section="summary",
            label="Total installed storage power",
            value=total_power_mw,
            unit="MW",
            capacity_mwh=total_capacity_mwh,
            power_mw=total_power_mw,
            systems=total_systems,
            average_epr_h=average_epr_h,
            notes="Cumulative German registered battery storage stock, MaStR-derived public aggregate.",
            sort_order=2,
        ),
        _base_row(
            section="summary",
            label="Registered BESS units",
            value=total_systems,
            unit="systems",
            capacity_mwh=total_capacity_mwh,
            power_mw=total_power_mw,
            systems=total_systems,
            average_epr_h=average_epr_h,
            notes="Rounded public aggregate; dominated by PV home storage systems.",
            sort_order=3,
        ),
        _base_row(
            section="summary",
            label="Average energy-to-power ratio",
            value=average_epr_h,
            unit="h",
            capacity_mwh=total_capacity_mwh,
            power_mw=total_power_mw,
            systems=total_systems,
            average_epr_h=average_epr_h,
            notes="Capacity divided by power across the public aggregate.",
            sort_order=4,
        ),
    ]

    segment_rows = [
        ("Home storage", 20_750.0, None, 2_399_000, "PV home batteries; capacity stock reported for March 2026."),
        ("Commercial storage", 1_420.0, None, None, "Commercial/industrial segment stock reported for March 2026."),
        ("Large-scale storage", 5_060.0, None, 489, "Large battery systems reported for March 2026."),
    ]
    for idx, (label, capacity_mwh, power_mw, systems, notes) in enumerate(segment_rows, start=1):
        rows.append(
            _base_row(
                section="segment",
                label=label,
                value=capacity_mwh,
                unit="MWh",
                capacity_mwh=capacity_mwh,
                power_mw=power_mw,
                systems=systems,
                share_pct=capacity_mwh / total_capacity_mwh * 100.0,
                notes=notes,
                sort_order=idx,
            )
        )

    epr_rows = [
        ("2h", 20_750.0, "Mostly home storage and short-duration systems."),
        ("4h", 1_420.0, "Mostly commercial systems; bucketed for education from segment aggregate."),
        ("6h+", 5_060.0, "Large-scale storage bucket; use raw MaStR processing for exact unit-level EPR."),
    ]
    for idx, (label, capacity_mwh, notes) in enumerate(epr_rows, start=1):
        rows.append(
            _base_row(
                section="epr_distribution",
                label=label,
                value=capacity_mwh,
                unit="MWh",
                capacity_mwh=capacity_mwh,
                share_pct=capacity_mwh / total_capacity_mwh * 100.0,
                notes=notes,
                sort_order=idx,
            )
        )

    state_rows = [
        ("Nordrhein-Westfalen", 435.8, 216.4, 22_081),
        ("Bayern", 395.4, 216.2, 18_630),
        ("Sachsen-Anhalt", 343.3, 159.6, 2_405),
        ("Baden-Wuerttemberg", 223.7, 131.7, 17_833),
        ("Niedersachsen", 222.3, 114.8, 12_106),
    ]
    for idx, (label, capacity_mwh, power_mw, systems) in enumerate(state_rows, start=1):
        rows.append(
            _base_row(
                section="bundesland_top5",
                label=label,
                value=capacity_mwh,
                unit="MWh",
                capacity_mwh=capacity_mwh,
                power_mw=power_mw,
                systems=systems,
                average_epr_h=capacity_mwh / power_mw if power_mw else None,
                notes="Q1 2026 newly commissioned capacity by Bundesland, not cumulative stock.",
                sort_order=idx,
            )
        )

    return pd.DataFrame(rows).sort_values(["section", "sort_order"]).reset_index(drop=True)


def _first_present(columns: Iterable[str], candidates: Iterable[str]) -> str | None:
    normalized = {column.lower().strip(): column for column in columns}
    for candidate in candidates:
        match = normalized.get(candidate.lower().strip())
        if match is not None:
            return match
    return None


def _numeric(series: pd.Series) -> pd.Series:
    """Parse German/English decimal strings and return numeric values."""

    if pd.api.types.is_numeric_dtype(series):
        return pd.to_numeric(series, errors="coerce")
    cleaned = series.astype(str).str.replace(".", "", regex=False).str.replace(",", ".", regex=False)
    return pd.to_numeric(cleaned, errors="coerce")


def _capacity_to_mwh(raw: pd.DataFrame, column: str) -> pd.Series:
    values = _numeric(raw[column])
    return values / 1000.0 if "kwh" in column.lower() else values


def _power_to_mw(raw: pd.DataFrame, column: str) -> pd.Series:
    values = _numeric(raw[column])
    return values / 1000.0 if "kw" in column.lower() and "mw" not in column.lower() else values


def _classify_epr(duration_h: float) -> str:
    if duration_h <= 2.0:
        return "2h"
    if duration_h <= 4.0:
        return "4h"
    return "6h+"


def _classify_segment(power_mw: float, capacity_mwh: float) -> str:
    if power_mw >= 1.0 or capacity_mwh >= 1.0:
        return "Large-scale storage"
    if power_mw <= 0.03 or capacity_mwh <= 0.05:
        return "Home storage"
    return "Commercial storage"


def process_mastr_bess_units(raw_units: pd.DataFrame) -> pd.DataFrame:
    """Aggregate a MaStR storage/unit export into dashboard-ready BESS stats."""

    capacity_col = _first_present(
        raw_units.columns,
        [
            "Nutzbare Speicherkapazitaet in kWh",
            "Nutzbare Speicherkapazität in kWh",
            "usable_storage_capacity_kwh",
            "usable_storage_capacity",
            "capacity_kwh",
            "capacity_mwh",
        ],
    )
    power_col = _first_present(
        raw_units.columns,
        [
            "Nettonennleistung der Einheit",
            "net_nominal_power",
            "net_nominal_power_kw",
            "net_nominal_power_mw",
            "power_kw",
            "power_mw",
        ],
    )
    state_col = _first_present(raw_units.columns, ["Bundesland", "state", "federal_state"])
    status_col = _first_present(raw_units.columns, ["Betriebs-Status", "unit_status", "operational_status"])
    id_col = _first_present(raw_units.columns, ["MaStR-Nr. der Einheit", "unit_mastr_number", "id"])

    missing = [name for name, column in {"capacity": capacity_col, "power": power_col}.items() if column is None]
    if missing:
        raise ValueError(f"MaStR raw export missing required columns: {missing}")

    assert capacity_col is not None
    assert power_col is not None

    units = raw_units.copy()
    if status_col is not None:
        status = units[status_col].astype(str).str.lower()
        active_mask = status.str.contains("betrieb|operating|active|in operation", regex=True, na=False)
        if active_mask.any():
            units = units.loc[active_mask].copy()

    units["capacity_mwh"] = _capacity_to_mwh(units, capacity_col)
    units["power_mw"] = _power_to_mw(units, power_col)
    units = units[(units["capacity_mwh"] > 0) & (units["power_mw"] > 0)].copy()
    if units.empty:
        raise ValueError("MaStR raw export contains no active BESS units with positive capacity and power.")

    units["epr_h"] = units["capacity_mwh"] / units["power_mw"]
    units["epr_bucket"] = units["epr_h"].map(_classify_epr)
    units["segment"] = [
        _classify_segment(power_mw, capacity_mwh)
        for power_mw, capacity_mwh in zip(units["power_mw"], units["capacity_mwh"], strict=False)
    ]
    if state_col is not None:
        units["bundesland"] = units[state_col].fillna("Unknown").astype(str)
    else:
        units["bundesland"] = "Unknown"

    total_capacity_mwh = float(units["capacity_mwh"].sum())
    total_power_mw = float(units["power_mw"].sum())
    systems = int(units[id_col].nunique()) if id_col is not None else int(len(units))
    average_epr_h = total_capacity_mwh / total_power_mw

    rows: list[dict[str, object]] = [
        _base_row(
            section="summary",
            label="Total installed storage capacity",
            value=total_capacity_mwh,
            unit="MWh",
            capacity_mwh=total_capacity_mwh,
            power_mw=total_power_mw,
            systems=systems,
            average_epr_h=average_epr_h,
            notes="Processed from MaStR storage/unit export.",
            sort_order=1,
        ),
        _base_row(
            section="summary",
            label="Total installed storage power",
            value=total_power_mw,
            unit="MW",
            capacity_mwh=total_capacity_mwh,
            power_mw=total_power_mw,
            systems=systems,
            average_epr_h=average_epr_h,
            notes="Processed from MaStR storage/unit export.",
            sort_order=2,
        ),
        _base_row(
            section="summary",
            label="Registered BESS units",
            value=systems,
            unit="systems",
            capacity_mwh=total_capacity_mwh,
            power_mw=total_power_mw,
            systems=systems,
            average_epr_h=average_epr_h,
            notes="Processed from MaStR storage/unit export.",
            sort_order=3,
        ),
        _base_row(
            section="summary",
            label="Average energy-to-power ratio",
            value=average_epr_h,
            unit="h",
            capacity_mwh=total_capacity_mwh,
            power_mw=total_power_mw,
            systems=systems,
            average_epr_h=average_epr_h,
            notes="Capacity divided by power across processed units.",
            sort_order=4,
        ),
    ]

    for idx, (bucket, group) in enumerate(units.groupby("epr_bucket", sort=False), start=1):
        capacity_mwh = float(group["capacity_mwh"].sum())
        power_mw = float(group["power_mw"].sum())
        rows.append(
            _base_row(
                section="epr_distribution",
                label=bucket,
                value=capacity_mwh,
                unit="MWh",
                capacity_mwh=capacity_mwh,
                power_mw=power_mw,
                systems=int(len(group)),
                average_epr_h=capacity_mwh / power_mw,
                share_pct=capacity_mwh / total_capacity_mwh * 100.0,
                notes="Bucketed by unit-level energy-to-power ratio.",
                sort_order=idx,
            )
        )

    top_states = (
        units.groupby("bundesland", as_index=False)
        .agg(capacity_mwh=("capacity_mwh", "sum"), power_mw=("power_mw", "sum"), systems=("capacity_mwh", "size"))
        .sort_values("capacity_mwh", ascending=False)
        .head(5)
    )
    for idx, row in enumerate(top_states.itertuples(index=False), start=1):
        rows.append(
            _base_row(
                section="bundesland_top5",
                label=str(row.bundesland),
                value=float(row.capacity_mwh),
                unit="MWh",
                capacity_mwh=float(row.capacity_mwh),
                power_mw=float(row.power_mw),
                systems=int(row.systems),
                average_epr_h=float(row.capacity_mwh) / float(row.power_mw),
                notes="Top five Bundeslaender by processed MaStR BESS capacity.",
                sort_order=idx,
            )
        )

    for idx, (segment, group) in enumerate(units.groupby("segment", sort=False), start=1):
        capacity_mwh = float(group["capacity_mwh"].sum())
        power_mw = float(group["power_mw"].sum())
        rows.append(
            _base_row(
                section="segment",
                label=segment,
                value=capacity_mwh,
                unit="MWh",
                capacity_mwh=capacity_mwh,
                power_mw=power_mw,
                systems=int(len(group)),
                average_epr_h=capacity_mwh / power_mw,
                share_pct=capacity_mwh / total_capacity_mwh * 100.0,
                notes="Segment classified by simple power/capacity thresholds.",
                sort_order=idx,
            )
        )

    return pd.DataFrame(rows).sort_values(["section", "sort_order"]).reset_index(drop=True)


def load_raw_mastr_export(raw_path: str | Path) -> pd.DataFrame:
    """Load a local MaStR export from CSV, Parquet, or Excel."""

    path = Path(raw_path)
    if path.suffix.lower() == ".parquet":
        return pd.read_parquet(path)
    if path.suffix.lower() in {".xlsx", ".xls"}:
        return pd.read_excel(path)
    return pd.read_csv(path)


def load_open_mastr_storage_table(table: str = "storage_extended") -> pd.DataFrame:
    """Download/read MaStR storage data with open-mastr and return a DataFrame.

    This can take significant time and disk space because open-mastr mirrors the
    public bulk registry into a local SQLite database.
    """

    from open_mastr import Mastr

    db = Mastr()
    db.download(data=["storage", "storage_units"], date="today")
    db.translate()
    return pd.read_sql(sql=table, con=db.engine)


def build_mastr_bess_stats(
    raw_path: str | Path | None = None,
    *,
    use_open_mastr: bool = False,
) -> pd.DataFrame:
    """Build BESS stats from raw MaStR data or the shipped April 2026 snapshot."""

    if raw_path is not None:
        return process_mastr_bess_units(load_raw_mastr_export(raw_path))
    if use_open_mastr:
        return process_mastr_bess_units(load_open_mastr_storage_table())
    return curated_april_2026_bess_snapshot()


def save_mastr_bess_stats(
    stats: pd.DataFrame | None = None,
    path: str | Path = PROCESSED_STATS_PATH,
) -> Path:
    """Persist processed MaStR BESS statistics as Parquet."""

    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    stats_to_save = curated_april_2026_bess_snapshot() if stats is None else stats
    stats_to_save.to_parquet(output_path, index=False)
    return output_path


def load_mastr_bess_stats(path: str | Path = PROCESSED_STATS_PATH) -> pd.DataFrame:
    """Load processed stats, creating the packaged snapshot if it is missing."""

    stats_path = Path(path)
    if not stats_path.exists():
        save_mastr_bess_stats(path=stats_path)
    return pd.read_parquet(stats_path)
